## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.26 pinned at 3.26.2 (nixpkgs 79b3d4bcae8c).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.26" args
