# Getting back into a machine when something in the initrd goes wrong, at
# the console. On by default for every host.
#
# `boot.initrd.systemd.emergencyAccess` defaults to `false` in upstream
# NixOS, which doesn't mean "no password" — sulogin treats it as a
# genuinely LOCKED account, refusing the console outright ("Cannot open
# access to console, the root account is locked") if any initrd unit fails
# and drops to emergency mode. That's a dead end at the one moment someone
# most needs a shell — the console, sitting right in front of the machine,
# with no network yet. `true` here means unauthenticated emergency access;
# the bar for that is already physical console access to the machine, which
# is the same bar for booting it off other media anyway.
#
# A remote-unlock SSH server in the initrd (so an encrypted-root machine
# stuck waiting on a passphrase could be reached over the network) used to
# live in this file too. Cut for now: `boot.initrd.secrets` copies its host
# key from a real file on disk at the point the system is BUILT, but this
# module only ever generated that file via `system.activationScripts` —
# which runs on `nixos-install` only AFTER that first build already
# happened. A fresh install's very first build therefore never had a key to
# bake in, so the initrd's sshd could never come up correctly on the one
# boot that would need it most. `unlock-host` (utilities.nix) and the
# `initrdSshPort` host-config field are left in place — they're inert until
# this comes back properly sequenced (the key would need to be generated by
# the installer itself, before the first `nixos-install` build, not by an
# activation script) — but nothing in this file talks to the network
# before the real system is up.
{ ... }:
{
  boot.initrd.systemd.emergencyAccess = true;
}
