# Kanata keyboard remapping — the layer/mod/nav mechanism gisnix ships,
# generated by ./kanata-config.nix. See docs/user/keyboard.md for the key
# reference; this file is just the systemd/uinput wiring.
#
# Add your user to the uinput group in your host config:
#   users.groups.uinput.members = [ "your-username" ];
{
  config,
  pkgs,
  lib,
  hostConfig,
  ...
}:
let
  # Timing (milliseconds). tapTimeout/holdTimeout govern the space/menu
  # hold into the navigation layer; modTapTimeout/modHoldTimeout govern the
  # home-row mods. Raise either hold value if taps are misfiring as holds
  # on your hardware; lower it if the modifiers feel sluggish to arm.
  tapTimeout = 280;
  holdTimeout = 280;

  # Which xkb layout this host's keyboards type under. A host knob
  # (`kanataLayout` in hosts/<name>/config.nix) rather than a hardcoded
  # value, because it changes which physical key `@` and `-` live under —
  # see kanata-config.nix's own `layout` parameter for why.
  layout = hostConfig.kanataLayout or "us";
in
{
  hardware.uinput.enable = true;

  # Passwordless sudo for the toggle/status scripts below.
  security.sudo.extraRules = [
    {
      groups = [ "wheel" ];
      commands = [
        {
          command = "/run/current-system/sw/bin/systemctl start kanata-*";
          options = [ "NOPASSWD" ];
        }
        {
          command = "/run/current-system/sw/bin/systemctl stop kanata-*";
          options = [ "NOPASSWD" ];
        }
        {
          command = "/run/current-system/sw/bin/systemctl restart kanata-*";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  services.kanata = {
    enable = true;
    keyboards = {
      keyboard = {
        devices = [ ]; # match every keyboard

        # concurrent-tap-hold is required by defchordsv2 whenever a chord
        # file is in use; harmless when none is.
        extraDefCfg = ''
          process-unmapped-keys yes
          concurrent-tap-hold yes
        '';

        config = import ./kanata-config.nix {
          inherit tapTimeout holdTimeout layout;
        };
      };
    };
  };

  # Upstream's kanata module sets no `Restart=`, so systemd's default
  # (Restart=no) applies and a crash is terminal: the keyboard silently
  # reverts to its raw layout — no home-row mods, no nav layer — until
  # someone notices and restarts it by hand. A crash here is transient
  # (kanata check-builds every config it generates, so a unit that starts
  # at all has a valid one), so restarting is the right response. The
  # start limit is the backstop for a genuinely unstartable instance.
  systemd.services = lib.mapAttrs' (
    name: _:
    lib.nameValuePair "kanata-${name}" {
      startLimitIntervalSec = 60;
      startLimitBurst = 5;
      serviceConfig = {
        Restart = "on-failure";
        RestartSec = 3;
      };
    }
  ) config.services.kanata.keyboards;

  environment.systemPackages = with pkgs; [
    kanata

    (writeShellScriptBin "kanata-toggle" ''
      #!/usr/bin/env bash
      mapfile -t SERVICES < <(systemctl list-units --all --plain --no-legend 'kanata-*.service' | awk '{print $1}')
      [ ''${#SERVICES[@]} -eq 0 ] && { echo "No kanata services found"; exit 1; }

      if systemctl is-active --quiet "''${SERVICES[0]}"; then
        for s in "''${SERVICES[@]}"; do sudo systemctl stop "$s"; done
        notify-send -u normal -t 2000 "Kanata" "Keyboard remapping DISABLED" -i input-keyboard
        echo "Kanata disabled (''${SERVICES[*]})"
      else
        for s in "''${SERVICES[@]}"; do sudo systemctl start "$s"; done
        notify-send -u normal -t 2000 "Kanata" "Keyboard remapping ENABLED" -i input-keyboard
        echo "Kanata enabled (''${SERVICES[*]})"
      fi
    '')

    (writeShellScriptBin "kanata-status" ''
      #!/usr/bin/env bash
      systemctl list-units --all --plain --no-legend 'kanata-*.service' | awk '{print $1, $3}'
    '')

    (writeShellScriptBin "kanata-debug" ''
      #!/usr/bin/env bash
      echo "=== Kanata Keyboard Debugging ==="
      echo "1. Kanata service status:"
      systemctl status kanata-keyboard --no-pager

      echo -e "\n2. Available input devices:"
      ls -la /dev/input/by-path/ | grep -i kbd || echo "No keyboard devices found"

      echo -e "\n3. Kanata logs (last 20 lines):"
      journalctl -u kanata-keyboard --no-pager -n 20

      echo -e "\n4. uinput device:"
      ls -la /dev/uinput 2>/dev/null || echo "/dev/uinput not found"

      echo -e "\n5. Groups for current user:"
      groups
    '')

    (writeShellScriptBin "kanata-test" ''
      #!/usr/bin/env bash
      echo "Testing kanata with verbose output (Ctrl+C to exit)..."
      sudo kanata --cfg /etc/kanata/keyboard.kbd --debug
    '')
  ];
}
