"""The three-pane bundle chooser behind `gisnix configure`.

    ┌──────────────────┬────────────────────────────────┐
    │ bundles          │ what this bundle installs      │
    │ ● base           │   • firefox                    │   upper ¾
    │ ○ desktop-gis    │   • brave                      │
    ├──────────────────┴────────────────────────────────┤
    │ detail of whatever is highlighted                 │   lower ¼
    └───────────────────────────────────────────────────┘

Tab moves between the two upper panes, and the bottom pane follows whichever
has focus: the bundle on the left, or the individual package on the right.
Choosing between `desktop-multimedia` and `desktop-productivity` from their
names alone is guesswork — seeing that one of them is what installs `obs` is
not.

WHERE THE PACKAGE DESCRIPTIONS COME FROM

`docs/references/software.json`, written by
`docs/scripts/generate-software-catalogue.py` out of nixpkgs metadata. That
generator runs a `nix eval` over every host and takes minutes; a pane that
redraws on every cursor movement has milliseconds, so it reads the answer
that run already worked out rather than asking again.

The consequence is honest and stated in the pane: a package no host installs
is not in the index, and is shown as "not in the catalogue" rather than as
having no description. The index is regenerated by the docs workflow.

WHY TEXTUAL

`gum choose` is a single column with no cursor-moved event, so there is
nothing to hang a live pane on — a hard limit of the tool. Textual comes from
the flake (`pythonDeps` in `utils/commands.json`), never from pip. If it is
somehow absent, `utils/configure.py` falls back to the gum picker: nothing
here is load-bearing for correctness, since every guarantee about what gets
written lives in `utils/lib/hostconfig.py`, which this only hands a set of
names to.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import bundleinfo as I  # noqa: E402
import moduleedit as M  # noqa: E402
import hostconfig as H  # noqa: E402

from textual.app import App, ComposeResult  # noqa: E402
from textual.containers import Horizontal, VerticalScroll  # noqa: E402
from textual.widgets import Footer, Header, Input, OptionList, Static  # noqa: E402
from textual.widgets.option_list import Option  # noqa: E402

ON = "●"
IMPLIED = "◐"
OFF = "○"
#: Radio marks, for members of a one-of group. Deliberately a different shape
#: from the checkbox marks above: these are alternatives, and picking one
#: unpicks its siblings, which a row that looks identical to a checkbox would
#: not lead anyone to expect.
PICKED = "◉"
UNPICKED = "◯"


@dataclass
class Result:
    """What the chooser hands back: a selection, and any module edits staged."""

    selected: set[str]
    #: module path -> the packages it should end up installing.
    edits: dict[Path, set[str]]
    #: choice key -> the member picked, e.g. {"locale": "pt-en",
    #: "kernel": "latest"}. These are scalar keys in config.nix, not entries
    #: in `bundles`, because their members are alternatives.
    choices: dict[str, str] = field(default_factory=dict)

INDEX_PATH = H.REPO_ROOT / "docs" / "references" / "software.json"


@lru_cache(maxsize=1)
def package_index() -> dict[str, dict]:
    """package name -> nixpkgs metadata, or {} when the index is absent."""
    try:
        return json.loads(INDEX_PATH.read_text())
    except (OSError, ValueError):
        return {}


def _nearest_selectable(options: list[Option], at: int) -> int:
    """The closest index to `at` that is not a disabled row.

    Module headings are disabled, so a restored position can land on one.
    Textual will not highlight a disabled option, and asking it to is how the
    cursor ends up somewhere unrelated.
    """
    if not options[at].disabled:
        return at
    for step in range(1, len(options)):
        for candidate in (at - step, at + step):
            if 0 <= candidate < len(options) and not options[candidate].disabled:
                return candidate
    return at


class BundleChooser(App):
    """Pick a host's bundles, seeing what each one installs."""

    CSS = """
    #panes { height: 3fr; }
    /* height: 100% on both, or a pane sizes itself to its contents and a
       bundle with four packages draws a stunted box beside a full-height
       one. The two upper panes are a single rectangle split down the
       middle; they should look like one. */
    #bundles {
        width: 42%;
        height: 100%;
        border: round $primary;
        padding: 0 1;
    }
    #packages {
        width: 1fr;
        height: 100%;
        border: round $primary;
        padding: 0 1;
    }
    #detail-pane {
        height: 1fr;
        border: round $accent;
        padding: 0 2;
    }
    #detail { width: 100%; }
    #search { display: none; border: tall $accent; }
    #search.visible { display: block; }
    #bundles:focus, #packages:focus { border: thick $accent; }
    """

    BINDINGS = [
        ("tab", "switch", "other pane"),
        ("space", "toggle", "toggle"),
        ("slash", "search", "filter"),
        ("e", "edit_mode", "edit packages"),
        ("d", "delete_package", "delete (edit mode)"),
        ("a", "add_package", "add (edit mode)"),
        ("g", "new_group", "new bundle (edit mode)"),
        ("ctrl+s", "accept", "save"),
        ("escape", "cancel", "cancel"),
        ("q", "cancel", "cancel"),
    ]

    def __init__(
        self, host: str, selected: set[str], choices: dict[str, str] | None = None
    ) -> None:
        super().__init__()
        self.host = host
        self.catalogue = H.catalogue()
        #: The one-of groups and their members, folded into the same tree as
        #: the bundles. They were a separate `gum choose` prompt after this
        #: app exited, which meant the menu whose whole job is to show
        #: everything a machine can take did not show the kernel or the
        #: locale at all.
        self.groups = H.choice_groups()
        #: choice key -> the member currently picked, or absent for none.
        self.choices = dict(choices or {})
        self.selected = set(selected)
        #: (module, package) pairs currently listed on the right, by index.
        self.listed: list[tuple[str, str]] = []
        #: Current filter. Matches a bundle's own name or any package in it,
        #: so typing "firefox" answers "which bundle would install that?" —
        #: the question a name-only filter cannot.
        self.query = ""
        #: Edit mode rewrites the MODULES, not this host's config.nix, so a
        #: change here reaches every host taking the bundle. Nothing touches
        #: disk until ctrl+s, and then only through moduleedit.apply, which
        #: refuses anything that does not parse.
        self.editing = False
        #: module path -> packages staged for addition / removal.
        self.added: dict[Path, set[str]] = {}
        self.removed: dict[Path, set[str]] = {}
        #: What the one input box is currently for: "filter", "add", "group".
        self.mode = "filter"
        #: Edit mode rewrites the MODULES, not this host's config.nix, so a
        #: change here reaches every host taking the bundle. Nothing touches
        #: disk until ctrl+s, and then only through moduleedit.apply, which
        #: refuses anything that does not parse.
        self.editing = False
        #: module path -> packages staged for addition / removal.
        self.added: dict[Path, set[str]] = {}
        self.removed: dict[Path, set[str]] = {}
        #: What the one input box is currently for: "filter", "add", "group".
        self.mode = "filter"
        self.title = f"gisnix configure — {host}"

    # ── layout ────────────────────────────────────────────────────────────

    def compose(self) -> ComposeResult:
        yield Header()
        yield Input(placeholder="filter by bundle or package name…", id="search")
        with Horizontal(id="panes"):
            yield OptionList(*self._bundle_options(), id="bundles")
            yield OptionList(id="packages")
        with VerticalScroll(id="detail-pane"):
            yield Static(id="detail")
        yield Footer()

    def on_mount(self) -> None:
        self._count_subtitle()
        self.query_one("#bundles", OptionList).focus()

    def _count_subtitle(self) -> None:
        if self.editing:
            pending = sum(len(v) for v in self.added.values()) + sum(
                len(v) for v in self.removed.values()
            )
            self.sub_title = (
                f"EDIT MODE — {pending} staged · d deletes · a adds · "
                "g new bundle · e leaves · ctrl+s writes"
            )
            return
        shown = ""
        if self.query:
            shown = f" · showing {len(self._visible())} matching {self.query!r}"
        self.sub_title = (
            f"{len(self.selected)} of {len(self.catalogue)} bundles{shown} · "
            "/ filters · tab switches pane · space toggles · ctrl+s writes"
        )

    # ── left pane: the bundles ────────────────────────────────────────────

    def _implied(self) -> dict[str, list[str]]:
        """Bundles arriving through `implies` that were not chosen directly.

        Without this the left pane lies. A host taking `services-device-input`
        gets `services-device` too — the child names it in `implies` — but the
        parent's row showed a hollow circle, which reads as "not installed".
        """
        reasons: dict[str, list[str]] = {}
        for name in sorted(self.selected):
            for pulled in H.resolve([name])[1:]:
                if pulled not in self.selected:
                    reasons.setdefault(pulled, []).append(name)
        return reasons

    def _member_row(self, row: dict) -> str:
        """A radio row: `◉ kernel · latest`, indented under its parent."""
        picked = self.choices.get(row["key"]) == row["value"]
        mark = f"[green]{PICKED}[/green]" if picked else f"[dim]{UNPICKED}[/dim]"
        label = f"{row['key']} · {row['value']}"
        if not picked:
            label = f"[dim]{label}[/dim]"
        tags = ["[dim]one of[/dim]"]
        note = row["group"].get("choiceNotes", {}).get(row["value"])
        if note:
            tags.append(f"[yellow]{note}[/yellow]")
        return f"{'  ' * row['depth']}{mark} {label}  " + " ".join(tags)

    def _bundle_row(self, bundle: dict, implied: dict[str, list[str]]) -> str:
        if bundle.get("kind") == "member":
            return self._member_row(bundle)
        name = bundle["name"]
        on = name in self.selected
        via = implied.get(name)
        if on:
            mark = f"[green]{ON}[/green]"
        elif via:
            mark = f"[blue]{IMPLIED}[/blue]"
        else:
            mark = f"[dim]{OFF}[/dim]"
        indent = "  " * bundle.get("depth", 0)
        label = name if on or via else f"[dim]{name}[/dim]"

        tags = []
        if via and not on:
            tags.append(f"[blue]via {via[0]}[/blue]")
        if bundle.get("required"):
            tags.append("[yellow]req[/yellow]")
        if bundle.get("optIn"):
            tags.append("[yellow]opt-in[/yellow]")
        count = I.counts().get(name, 0)
        if count:
            tags.append(f"[dim]{count}[/dim]")
        return f"{indent}{mark} {label}  " + " ".join(tags)

    def _member_rows(self, group: dict, depth: int) -> list[dict]:
        """One row per alternative in a one-of group.

        No header row above them. A header would have to be either selectable
        and inert — a row that ignores the key everything else responds to —
        or skipped by the cursor, which puts the group's description where
        nothing can highlight it. Naming the key on each row costs six
        characters and needs neither.
        """
        key = group["choiceKey"]
        prefix = group.get("modulePrefix", key)
        return [
            {
                "kind": "member",
                "name": f"{key}={value}",
                "key": key,
                "value": value,
                "group": group,
                "path": group["path"],
                "depth": depth,
                # A pseudo-bundle of exactly this member's module, so the
                # package pane and the detail pane can treat it as any other.
                "modules": [f"{prefix}-{value}.nix"],
                "description": group["description"],
            }
            for value in group["values"]
        ]

    def _rows(self) -> list[dict]:
        """The left pane's contents: bundles, with each one-of group's members
        nested under the bundle whose directory contains them.

        `software/base/kernel/` sits inside `software/base/`, so the two
        kernel rows appear indented under `base` — which is where someone
        looking for "what kernel does this machine boot" would look for them.
        A group with no enclosing bundle, as `software/locale/` has none,
        goes at the top level.
        """
        paths = {b["path"] for b in self.catalogue}
        rows: list[dict] = []
        for bundle in self.catalogue:
            rows.append(bundle | {"kind": "bundle"})
            for group in self.groups:
                if H.parent_path(group["path"], paths) == bundle["path"]:
                    rows += self._member_rows(group, bundle.get("depth", 0) + 1)
        for group in self.groups:
            if H.parent_path(group["path"], paths) is None:
                rows += self._member_rows(group, 0)
        return rows

    def _visible(self) -> list[dict]:
        return [b for b in self._rows() if I.matches(b, self.query)]

    def _bundle_options(self) -> list[Option]:
        implied = self._implied()
        visible = self._visible()
        if not visible:
            return [Option("[dim]nothing matches that[/dim]", disabled=True)]
        return [Option(self._bundle_row(b, implied), id=b["name"]) for b in visible]

    def _rebuild_bundles(self) -> None:
        """Redraw the left pane, keeping the cursor where it was."""
        pane = self.query_one("#bundles", OptionList)
        at = pane.highlighted
        pane.clear_options()
        pane.add_options(self._bundle_options())
        if at is not None:
            pane.highlighted = at
        self._count_subtitle()

    # ── right pane: what the highlighted bundle installs ──────────────────

    def _fill_packages(self, name: str, keep_cursor: bool = False) -> None:
        """Redraw the right pane.

        `keep_cursor` holds the position across a redraw caused by an EDIT.
        Deleting a package rebuilds the list, and without this the cursor
        snapped back to the top — so removing three packages from a module
        meant scrolling back down twice. Moving to a different bundle is the
        other case, and there the cursor should start at the top.
        """
        bundle = self._bundle(name)
        pane = self.query_one("#packages", OptionList)
        at = pane.highlighted if keep_cursor else None
        pane.clear_options()
        self.listed = []
        if bundle is None:
            return

        options: list[Option] = []
        for module in I.summarise(bundle)["modules"]:
            shown = [
                p for p in module["packages"] if not self.query or self.query in p.lower()
            ]
            # A module with nothing left to show is noise while filtering.
            if self.query and not shown:
                continue
            path = I.REPO_ROOT / "software" / bundle["path"] / module["name"]
            staged_out = self.removed.get(path, set())
            staged_in = sorted(self.added.get(path, set()))
            options.append(Option(f"[dim]{module['name']}[/dim]", disabled=True))
            for package in staged_in:
                if self.query and self.query not in package.lower():
                    continue
                options.append(
                    Option(
                        f"  [green]+ {package}[/green] [dim](staged — d undoes)[/dim]",
                        id=f"{len(self.listed)}",
                    )
                )
                self.listed.append((module["name"], package))
            for package in shown:
                locked = M.required_package(path, package)
                if locked:
                    _reason, hard = locked
                    # hard=True: the package cannot be absent (base/fish).
                    # hard=False: only this TEXT LINE is protected — the
                    # package itself is governed by an option or the bundle,
                    # which may default it off. "(required)" on that case
                    # reads as "always installed", which is exactly wrong.
                    icon, tag = ("🔒", "required") if hard else ("🧩", "built here")
                    options.append(
                        Option(
                            f"  [yellow]{icon}[/yellow] {package} [dim]({tag})[/dim]",
                            id=f"{len(self.listed)}",
                        )
                    )
                    self.listed.append((module["name"], package))
                    continue
                if package in staged_out:
                    options.append(
                        Option(
                            f"  [red]- {package}[/red] [dim](staged — d undoes)[/dim]",
                            id=f"{len(self.listed)}",
                        )
                    )
                    self.listed.append((module["name"], package))
                    continue
                known = package in package_index()
                mark = "[green]•[/green]" if known else "[yellow]•[/yellow]"
                options.append(Option(f"  {mark} {package}", id=f"{len(self.listed)}"))
                self.listed.append((module["name"], package))
            for service in module["enables"]:
                if self.query and self.query not in service.lower():
                    continue
                options.append(Option(f"  [blue]⚙[/blue] enables {service}", disabled=True))
            if not module["readable"] and not self.query:
                options.append(
                    Option("  [dim]no package list in this module[/dim]", disabled=True)
                )
        pane.add_options(options)
        if at is not None and options:
            pane.highlighted = _nearest_selectable(options, min(at, len(options) - 1))

    # ── bottom pane ───────────────────────────────────────────────────────

    def _bundle(self, name: str) -> dict | None:
        """Resolve a left-pane id, which may be a bundle or a group member."""
        return next((b for b in self._rows() if b["name"] == name), None)

    def _bundle_detail(self, name: str) -> str:
        bundle = self._bundle(name)
        if bundle is None:
            return ""
        if bundle.get("kind") == "member":
            return self._member_detail(bundle)
        info = I.summarise(bundle)
        out = [
            f"[bold]{name}[/bold]  [dim]software/{bundle['path']}/ · "
            f"{len(info['packages'])} packages in {len(info['modules'])} modules[/dim]",
            "",
            bundle["description"],
        ]
        if bundle.get("required"):
            out.append(f"[yellow]Required.[/yellow] {bundle.get('requiredReason', '')}.")
        if bundle.get("optIn"):
            out.append(
                f"[yellow]Opt-in.[/yellow] Never added when you take the group above "
                f"— {bundle.get('optInReason', '')}."
            )
        if bundle.get("implies"):
            out.append(f"[dim]Also brings in: {', '.join(bundle['implies'])}[/dim]")
        kids = H.children_of(name)
        if kids:
            out.append(f"[dim]Sub-bundles: {', '.join(kids)}[/dim]")
        out.append("")
        out.append("[dim]Tab to the package list to read about any one of them.[/dim]")
        return "\n".join(out)

    def _package_detail(self, index: int) -> str:
        if not 0 <= index < len(self.listed):
            return ""
        module, package = self.listed[index]
        meta = package_index().get(package)

        out = [f"[bold]{package}[/bold]  [dim]declared in {module}[/dim]", ""]
        if meta is None:
            out += [
                "[yellow]Not in the software catalogue.[/yellow] The catalogue is built"
                " from what the fleet's hosts actually install, so a package no host"
                " has yet will not be in it.",
                "",
                f"[dim]For the authoritative answer:  nix eval nixpkgs#{package}.meta"
                "[/dim]",
            ]
            return "\n".join(out)

        bundle = self._bundle(self._highlighted_bundle() or "")
        if bundle is not None:
            path = I.REPO_ROOT / "software" / bundle["path"] / module
            locked = M.required_package(path, package)
            if locked:
                reason, hard = locked
                if hard:
                    out.append(f"[yellow]Required — cannot be removed.[/yellow] {reason}.")
                else:
                    out.append(f"[yellow]Built by this flake.[/yellow] {reason}.")
                out.append("")

        out.append(meta.get("description") or "[dim]nixpkgs records no description.[/dim]")
        out.append("")
        if meta.get("homepage"):
            out.append(f"[dim]Home:[/dim] {meta['homepage']}")
        if meta.get("version"):
            out.append(f"[dim]Version:[/dim] {meta['version']}")
        hosts = meta.get("hosts") or []
        if hosts:
            out.append(f"[dim]Installed today on:[/dim] {', '.join(hosts)}")
        else:
            out.append("[dim]No host in the fleet installs this yet.[/dim]")
        return "\n".join(out)

    def _show(self, text: str) -> None:
        self.query_one("#detail", Static).update(text)
        self.query_one("#detail-pane", VerticalScroll).scroll_home(animate=False)

    def _refresh_detail(self) -> None:
        """Point the bottom pane at whichever upper pane has focus."""
        packages = self.query_one("#packages", OptionList)
        if packages.has_focus and packages.highlighted is not None:
            option = packages.get_option_at_index(packages.highlighted)
            if option.id is not None:
                self._show(self._package_detail(int(option.id)))
                return
        bundles = self.query_one("#bundles", OptionList)
        if bundles.highlighted is not None:
            name = bundles.get_option_at_index(bundles.highlighted).id
            if name:
                self._show(self._bundle_detail(name))

    # ── events ────────────────────────────────────────────────────────────

    def on_option_list_option_highlighted(
        self, event: OptionList.OptionHighlighted
    ) -> None:
        if event.option_list.id == "bundles":
            name = event.option.id
            if name:
                # A different bundle: start its package list at the top.
                self._fill_packages(name, keep_cursor=False)
        self._refresh_detail()

    def _member_detail(self, row: dict) -> str:
        group, key, value = row["group"], row["key"], row["value"]
        siblings = [v for v in group["values"] if v != value]
        out = [
            f"[bold]{key} · {value}[/bold]  [dim]software/{group['path']}/"
            f"{row['modules'][0]}[/dim]",
            "",
            group["description"],
            "",
            f"[yellow]One of {len(group['values'])}.[/yellow] Taking this drops "
            f"{', '.join(siblings) if siblings else 'the alternative'}. Written to "
            f"config.nix as [bold]{key} = \"{value}\";[/bold], not as an entry in "
            f"`bundles`.",
        ]
        note = group.get("choiceNotes", {}).get(value)
        if note:
            out.append(f"[yellow]{note}[/yellow]")
        detail = group.get("choiceDetails", {}).get(value)
        if detail:
            out.append(detail)
        return "\n".join(out)

    # ── actions ───────────────────────────────────────────────────────────

    def _highlighted_bundle(self) -> str | None:
        """The bundle under the cursor, by id rather than by position.

        Positions shift as the filter narrows the list; ids do not. The
        placeholder row shown when nothing matches carries no id, which is
        what makes toggling on an empty result a no-op rather than a crash.
        """
        pane = self.query_one("#bundles", OptionList)
        if pane.highlighted is None:
            return None
        return pane.get_option_at_index(pane.highlighted).id

    def action_switch(self) -> None:
        bundles = self.query_one("#bundles", OptionList)
        packages = self.query_one("#packages", OptionList)
        (bundles if packages.has_focus else packages).focus()
        self._refresh_detail()

    def action_toggle(self) -> None:
        """Take or drop the bundle under the LEFT pane's cursor.

        Only when that pane has focus. It used to work from either, on the
        reasoning that deciding while reading a package list is the natural
        moment — which ignored that the left cursor is then somewhere you are
        not looking. Space is a natural thing to press while browsing
        packages, the left pane starts on `base`, and the result was a run
        that refused to write because it had been asked to take the
        bootloader off the machine. Keys belong to the pane you can see.

        A bundle's children move with it, in both directions but not
        symmetrically:

        ON   its children come too, except any marked `optIn` — those are
             never added on a host's behalf.
        OFF  ALL its children go, opt-in included. A child names its parent
             in `implies`, so one left behind drags the parent back and the
             removal becomes a line that lies about the machine.

        Untick a child afterwards if you want the group without it; the
        interactive selection is written as-is, so it sticks.
        """
        if not self.query_one("#bundles", OptionList).has_focus:
            self.notify(
                "space takes a bundle — tab back to the list on the left. "
                "In the package pane, d deletes and a adds.",
                severity="warning",
            )
            return
        name = self._highlighted_bundle()
        if name is None:
            return

        row = self._bundle(name)
        if row is not None and row.get("kind") == "member":
            self._pick(row)
            return

        if name in self.selected:
            self.selected -= {name, *H.children_of(name)}
        else:
            self.selected.add(name)
            self.selected |= {c for c in H.children_of(name) if not H.opt_in(c)}
        self._rebuild_bundles()

    def _pick(self, row: dict) -> None:
        """Choose one member of a one-of group, unpicking its siblings.

        Pressing space on the member already picked clears the choice, but
        only for a group that HAS a no-member answer. `locale` does: a host
        may name none and get no locale module. `kernel` does not — a machine
        boots something — so its `choiceDefault` makes the row refuse to
        clear rather than silently leaving the host with no kernel row and no
        explanation.
        """
        key, value = row["key"], row["value"]
        group = row["group"]
        if self.choices.get(key) == value:
            if group.get("choiceDefault") is not None:
                self.notify(
                    f"{key} always has a value — pick a different one instead "
                    f"of clearing this.",
                    severity="warning",
                )
                return
            self.choices.pop(key, None)
        else:
            self.choices[key] = value
        self._rebuild_bundles()

    # ── filtering ─────────────────────────────────────────────────────────

    def _search(self) -> Input:
        return self.query_one("#search", Input)

    def action_search(self) -> None:
        """Open the filter box. `/` is muscle memory from fzf and less."""
        box = self._search()
        self.mode = "filter"
        box.placeholder = "filter by bundle or package name…"
        box.add_class("visible")
        box.focus()

    def _close_search(self, *, clear: bool) -> None:
        box = self._search()
        if clear:
            box.value = ""
            self.query = ""
            self._rebuild_bundles()
            self._reload_packages()
        box.remove_class("visible")
        self.query_one("#bundles", OptionList).focus()

    def on_input_changed(self, event: Input.Changed) -> None:
        if self.mode == "filter":
            self.query = event.value.strip().lower()
            self._rebuild_bundles()
            self._reload_packages()
        elif self.mode == "add":
            self._offer(M.suggestions(event.value))

    def _offer(self, names: list[str]) -> None:
        """Show completions in the right pane while a package is being typed."""
        pane = self.query_one("#packages", OptionList)
        pane.clear_options()
        self.listed = []
        if not names:
            pane.add_options([Option("[dim]keep typing…[/dim]", disabled=True)])
            return
        pane.add_options(
            [Option("[dim]already installed somewhere in the fleet:[/dim]", disabled=True)]
            + [Option(f"  [green]+[/green] {n}") for n in names]
        )

    def on_input_submitted(self, event: Input.Submitted) -> None:
        value = event.value.strip()
        if self.mode == "filter":
            self._close_search(clear=False)
        elif self.mode == "add":
            self._stage_add(value)
        elif self.mode == "group":
            self._make_group(value)

    def _stage_add(self, package: str) -> None:
        module = self._target_module()
        if module is None or not package:
            self._finish_input()
            return
        try:
            M.add(module, package)
        except M.Refused as refused:
            self.notify(str(refused), severity="error", timeout=10)
            return
        real, detail = M.exists_in_nixpkgs(package)
        if not real:
            self.notify(
                f"nixpkgs has no {package}: {detail}", severity="error", timeout=12
            )
            return
        self.removed.setdefault(module, set()).discard(package)
        self.added.setdefault(module, set()).add(package)
        reach = M.hosts_using(self._highlighted_bundle() or "")
        self.notify(
            f"staged: add {package} to {module.name} "
            f"({len(reach)} host{'' if len(reach) == 1 else 's'} affected)"
        )
        self._finish_input()

    def _make_group(self, path: str) -> None:
        if not path:
            self._finish_input()
            return
        try:
            directory = M.create_bundle(
                path, description=f"TODO: describe {path}. Written by gisnix configure."
            )
        except M.Refused as refused:
            self.notify(str(refused), severity="error", timeout=12)
            return
        # The registry is discovered from the filesystem, so a new bundle is
        # live the moment its directory exists — but this app read the
        # catalogue at startup and has to be told.
        self.catalogue = H.catalogue()
        self.notify(
            f"created software/{path}/ — it appears in the list now. "
            "git add it, or nix will not see it.",
            timeout=10,
        )
        del directory
        self._finish_input()
        self._rebuild_bundles()

    def _finish_input(self) -> None:
        box = self._search()
        box.value = ""
        box.placeholder = "filter by bundle or package name…"
        box.remove_class("visible")
        self.mode = "filter"
        self.query_one("#bundles", OptionList).focus()
        self._reload_packages()

    def _reload_packages(self, keep_cursor: bool = True) -> None:
        name = self._highlighted_bundle()
        if name:
            self._fill_packages(name, keep_cursor=keep_cursor)
        self._refresh_detail()

    # ── edit mode ─────────────────────────────────────────────────────────
    #
    # These change modules under software/, so they change every host taking
    # the bundle — not just the one being configured. Nothing reaches disk
    # here: edits are staged and written on ctrl+s by utils/configure.py,
    # which shows a diff per file and validates each one first.

    def action_edit_mode(self) -> None:
        self.editing = not self.editing
        self._count_subtitle()
        self._reload_packages()
        self.notify(
            "edit mode on — d deletes, a adds, g makes a bundle. "
            "Changes reach every host taking this bundle."
            if self.editing
            else "edit mode off",
            timeout=6,
        )

    def _module_under_cursor(self) -> tuple[Path, str] | None:
        """(module path, package) for the highlighted package, if any."""
        pane = self.query_one("#packages", OptionList)
        if pane.highlighted is None:
            return None
        option = pane.get_option_at_index(pane.highlighted)
        if option.id is None or not 0 <= int(option.id) < len(self.listed):
            return None
        module, package = self.listed[int(option.id)]
        bundle = self._bundle(self._highlighted_bundle() or "")
        if bundle is None:
            return None
        return I.REPO_ROOT / "software" / bundle["path"] / module, package

    def _target_module(self) -> Path | None:
        """Where an addition should go: the module the cursor is in."""
        under = self._module_under_cursor()
        if under:
            return under[0]
        bundle = self._bundle(self._highlighted_bundle() or "")
        if bundle is None or not bundle.get("modules"):
            return None
        return I.REPO_ROOT / "software" / bundle["path"] / bundle["modules"][0]

    def _staged(self, module: Path) -> set[str]:
        """What this module will install once the staged edits are applied."""
        current = set(I.packages_in(module)[0])
        return (current | self.added.get(module, set())) - self.removed.get(module, set())

    def action_delete_package(self) -> None:
        if not self.editing:
            self.notify("press e for edit mode first", severity="warning")
            return
        under = self._module_under_cursor()
        if under is None:
            self.notify("highlight a package in the right pane", severity="warning")
            return
        module, package = under

        # On a row that is already staged, d undoes it. Nothing has been
        # written yet, so the key that made the change is the obvious one to
        # take it back — and it means a mis-hit costs one keystroke.
        if package in self.removed.get(module, set()):
            self.removed[module].discard(package)
            self.notify(f"unstaged: {package} stays in {module.name}")
            self._reload_packages()
            return
        if package in self.added.get(module, set()):
            self.added[module].discard(package)
            self.notify(f"unstaged: {package} will not be added to {module.name}")
            self._reload_packages()
            return

        try:
            # Rehearse it now, so an edit that cannot be made says so while
            # the operator is still looking at it rather than at ctrl+s.
            M.remove(module, package)
        except M.Refused as refused:
            self.notify(str(refused), severity="error", timeout=10)
            return
        self.added.setdefault(module, set()).discard(package)
        self.removed.setdefault(module, set()).add(package)
        reach = M.hosts_using(self._highlighted_bundle() or "")
        self.notify(
            f"staged: remove {package} from {module.name} "
            f"({len(reach)} host{'' if len(reach) == 1 else 's'} affected)"
        )
        self._reload_packages()

    def action_add_package(self) -> None:
        if not self.editing:
            self.notify("press e for edit mode first", severity="warning")
            return
        if self._target_module() is None:
            self.notify("highlight a bundle with a module to add to", severity="warning")
            return
        box = self._search()
        box.placeholder = "package to add — tab completes from the catalogue"
        box.value = ""
        box.add_class("visible")
        box.focus()
        self.mode = "add"

    def action_new_group(self) -> None:
        if not self.editing:
            self.notify("press e for edit mode first", severity="warning")
            return
        box = self._search()
        box.placeholder = "new bundle: path/under/software  (e.g. desktop/audio)"
        box.value = ""
        box.add_class("visible")
        box.focus()
        self.mode = "group"

    # ── finishing ─────────────────────────────────────────────────────────

    def action_accept(self) -> None:
        edits = {
            module: self._staged(module)
            for module in set(self.added) | set(self.removed)
            if self._staged(module) != set(I.packages_in(module)[0])
        }
        self.exit(Result(self.selected, edits, dict(self.choices)))

    def action_cancel(self) -> None:
        """Escape backs out of the input first, and only then out of the app.

        Without this, reaching for escape to abandon a search would throw
        away the whole selection — the app's own escape binding fires because
        Input does not consume that key.
        """
        if self._search().has_focus or self.query:
            if self.mode != "filter":
                self._finish_input()
            else:
                self._close_search(clear=True)
            return
        self.exit(None)


def choose(
    host: str, selected: set[str], choices: dict[str, str] | None = None
) -> Result | None:
    """Run the chooser. Returns its Result, or None if cancelled."""
    return BundleChooser(host, selected, choices).run()
