## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.8 pinned at 3.8.0 (nixpkgs d93fb7b27207).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.8" args
