## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.24 pinned at 3.24.2 (nixpkgs f597e7e9fcf3).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.24" args
