## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 4.0 pinned at 4.0.3 (nixpkgs c27cdad491a9).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "4.0" args
