## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.22 pinned at 3.22.16 (nixpkgs 1b7a6a6e5766).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.22" args
