## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 2.10 pinned at 2.10.1 (nixpkgs d8516b0fe339).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "2.10" args
