## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.10 pinned at 3.10.13 (nixpkgs 0ffaecb6f044).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.10" args
