## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.38 pinned at 3.38.3 (nixpkgs 882842d2a908).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.38" args
