## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 1.8 pinned at 1.8.0 (nixpkgs ff15c31c37dc).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "1.8" args
