## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.36 pinned at 3.36.3 (nixpkgs 67b4bf1df4ae).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.36" args
