## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.28 pinned at 3.28.15 (nixpkgs 336eda0d07dc).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.28" args
