## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 2.6 pinned at 2.6.1 (nixpkgs 515b06ef2ae5).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "2.6" args
