## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.4 pinned at 3.4.8 (nixpkgs bea56ef8ba56).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.4" args
