## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 2.16 pinned at 2.16.2 (nixpkgs e8d3c74b499a).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "2.16" args
