## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.42 pinned at 3.42.3 (nixpkgs e6f23dc08d36).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.42" args
