## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.40 pinned at 3.40.15 (nixpkgs 9a01fad67a57).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.40" args
