## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 2.18 pinned at 2.18.28 (nixpkgs f06d8e0bf482).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "2.18" args
