#!/usr/bin/env python3
"""Generate docs/references/bundles.md from the bundle definitions.

Every fact on the page is read from the bundle.json files beside the modules
they describe. Nothing is written by hand, so the page cannot drift from the
configuration — which is the failure this whole exercise is about. The
previous documentation named a QGIS module by a path that had changed the
same afternoon.

Run from the repo root:  python3 docs/scripts/generate-bundle-docs.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(REPO_ROOT / "utils" / "lib"))

import bundleinfo  # noqa: E402
import bundles  # noqa: E402
import diagram  # noqa: E402

OUT = REPO_ROOT / "docs" / "references" / "bundles.md"


def _implication_diagram(all_bundles: list[dict]) -> str:
    """The `implies` graph as mermaid.

    `gisnix bundles --tree` has printed this in the terminal since the bundle
    system landed, and the reference page — the thing somebody reads when they
    are NOT at a terminal — had no picture of it at all. Derived from the same
    `implies` lists the resolver uses, so it cannot show a relationship the
    configuration does not have.
    """
    lines = ["graph LR"]
    seen: set[str] = set()

    def node(name: str) -> str:
        ident = name.replace("-", "_")
        if name not in seen:
            seen.add(name)
            marks = []
            bundle = next((b for b in all_bundles if b["name"] == name), {})
            if bundle.get("required"):
                marks.append("required")
            if bundle.get("optIn"):
                marks.append("opt-in")
            label = name + (f"<br/><i>{', '.join(marks)}</i>" if marks else "")
            lines.append(f'  {ident}["{label}"]')
        return ident

    edges = []
    for b in all_bundles:
        if b.get("selection") == "one-of":
            continue
        for implied in b.get("implies", []):
            edges.append((node(b["name"]), node(implied)))

    # Bundles with no edge either way would sit as loose boxes and say
    # nothing; the table below already lists them.
    for tail, head in edges:
        lines.append(f"  {tail} --> {head}")

    return diagram.render(
        "\n".join(lines),
        slug="bundle-implications",
        alt="Which bundles bring in which",
        rel_prefix="../assets/diagrams",
    )


def main() -> int:
    all_bundles = bundles.load()
    index = {b["name"]: b for b in all_bundles}

    # Who implies me — the reverse edge is what tells a reader why a bundle
    # they did not ask for ended up on their host.
    implied_by: dict[str, list[str]] = {b["name"]: [] for b in all_bundles}
    for b in all_bundles:
        for dep in b.get("implies", []):
            implied_by.setdefault(dep, []).append(b["name"])

    lines: list[str] = [
        "<!-- SPDX-FileCopyrightText: Tim Sutton -->",
        "<!-- SPDX-License-Identifier: MIT -->",
        "",
        "<span class=\"kz-eyebrow\">REFERENCE</span>",
        "",
        "# Software bundles",
        "",
        "<!-- Generated by docs/scripts/generate-bundle-docs.py."
        " Do not edit by hand. -->",
        "",
        "A **bundle is a directory** under `software/`. That is the whole idea:"
        " the taxonomy and the package sets are one system rather than two"
        " descriptions of the same tree that have to be kept in step.",
        "",
        "```text",
        "software/desktop/browsers/",
        "  bundle.json      what it is, what it needs, what is in it",
        "  browsers.nix     the module",
        "```",
        "",
        "A host names the bundles it wants and gets those, plus anything they"
        " imply, transitively:",
        "",
        "```nix",
        "# hosts/<name>/config.nix",
        "bundles = [",
        '  "desktop-browsers"',
        '  "desktop-productivity"',
        "];",
        "```",
        "",
        "A bundle's name is its path with slashes turned into hyphens, so the"
        " name always says where to look for it.",
        "",
        "## Turning bundles on and off",
        "",
        "`gisnix configure` is the menu. It reads the registry — every"
        " `bundle.json` under `software/` — and *not* the host's current"
        " `config.nix`, so the list you tick is always complete. A bundle"
        " added this morning is on the menu this afternoon, whether or not"
        " any host has heard of it.",
        "",
        "```bash",
        "gisnix configure                      # this machine, then tick the bundles",
        "gisnix configure myhost               # straight to myhost's bundles",
        "gisnix configure myhost --list        # what it takes today; changes nothing",
        "gisnix configure myhost --enable desktop-gis",
        "gisnix configure myhost --disable terminal-ai,desktop-games",
        "gisnix configure myhost --set base,desktop-browsers --locale za-en",
        "gisnix configure myhost --kernel latest",
        "gisnix configure myhost --enable security --dry-run",
        "```",
        "",
        "### The chooser",
        "",
        "Three panes. Bundles on the left, what the highlighted bundle"
        " installs on the right, and detail along the bottom:",
        "",
        "```text",
        "\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510",
        "\u2502 bundles          \u2502 what this bundle installs      \u2502",
        "\u2502 \u25cf base           \u2502   \u2022 firefox                    \u2502",
        "\u2502 \u25cb desktop-gis    \u2502   \u2022 brave                      \u2502",
        "\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524",
        "\u2502 detail of whatever is highlighted                 \u2502",
        "\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518",
        "```",
        "",
        "| Key | |",
        "| --- | --- |",
        "| <kbd>/</kbd> | filter both panes. Matches a bundle's name, any"
        " package in it, or any of its module filenames — so typing"
        " `firefox` answers *which bundle would install that?* Enter keeps"
        " the filter, escape clears it |",
        "| <kbd>tab</kbd> | move between the two upper panes. The bottom pane"
        " follows whichever has focus: the bundle on the left, the individual"
        " package on the right |",
        "| <kbd>space</kbd> | take or drop the highlighted bundle |",
        "| <kbd>g</kbd> | the bundle together with everything nested in it |",
        "| <kbd>e</kbd> | edit mode: change what the bundles *contain* |",
        "| <kbd>ctrl</kbd>+<kbd>s</kbd> | done — go on to the diff |",
        "| <kbd>esc</kbd> | cancel, writing nothing |",
        "",
        "Package descriptions in the bottom pane come from"
        " `docs/references/software.json`, which"
        " `docs/scripts/generate-software-catalogue.py` writes out of nixpkgs"
        " metadata. That generator runs a `nix eval` over every host and takes"
        " minutes; a pane redrawing on every keypress has milliseconds, so it"
        " reads the answer that run already worked out. A package no host"
        " installs is not in the index and is labelled as such rather than"
        " shown blank.",
        "",
        "The package lists themselves are read from the module source, which"
        " is a heuristic and says so: a package arriving by a route the reader"
        " does not follow is **missing** rather than wrong. `gisnix bundles"
        " <name>` is the authoritative view.",
        "",
        "Nothing is written until the diff has been shown and confirmed — and"
        " never at all if the result fails `nix-instantiate --parse`.",
        "",
        "### Bundles that cannot be removed",
        "",
        "A bundle marked `\"required\": true` is one `gisnix configure` will not"
        " take away from a host that has it. Unticking it is one keystroke,"
        " the result builds perfectly well, and then the machine does not"
        " come back — which you find out at a console it no longer runs an"
        " ssh daemon on.",
        "",
        "| Bundle | Why |",
        "| --- | --- |",
    ]

    for b in all_bundles:
        if b.get("required"):
            lines.append(f"| [`{b['name']}`](#{b['name']}) | {b.get('requiredReason', '—')} |")

    lines += [
        "",
        "This is **not** the same as \"every host must have it\". A host that"
        " imports its software directly, bypassing the bundle list entirely,"
        " takes neither — forcing the bundle onto it would change what that"
        " machine installs, a tool protecting you from one mistake by making"
        " a different one. The rule only bites on a host that already has"
        " the bundle. `--force` overrides it.",
        "",
        "### Groups bring their sub-bundles",
        "",
        "Some bundles nest: `services/device/input` sits inside"
        " `services/device`. The menu shows that as a tree, and switching a"
        " group **on** switches its children on with it — choosing"
        " `services-device` means choosing the keyboards and the printer too,"
        " because that is what the directory says the group is.",
        "",
        "Switching a group **off** takes its children with it, and that half"
        " is not optional. Every child names its parent in `implies`, so a"
        " host keeping `services-device-input` gets `services-device`"
        " whatever its `config.nix` says — dropping the parent alone changes"
        " nothing except to make the file claim something untrue. Opt-in"
        " children go too: `optIn` means *never added on your behalf*, not"
        " *never removed*, and dropping a group should not strand its parts.",
        "",
        "| | on | off |",
        "| --- | --- | --- |",
        "| **its children** | come too, except `optIn` ones | all go,"
        " `optIn` included |",
        "| **why** | taking a group means taking what is in it | a child left"
        " behind drags the parent back |",
        "",
        "Untick a child afterwards if you want the group without it — the"
        " chooser's answer is written as-is, so it sticks. `--no-cascade`"
        " turns off the *on* half; the *off* half always applies, because"
        " its absence produces a file that lies.",
        "",
        "The chooser shows a third state for this: a bundle you did not pick"
        " but which arrives anyway is drawn `◐ … via desktop-gis` rather than"
        " as switched off.",
        "",
        "#### Bundles that refuse to be taken this way",
        "",
        "A bundle marked `\"optIn\": true` is **never** selected on a host's"
        " behalf. It has to be asked for by name. Two carry the mark, and"
        " `gisnix configure` says so rather than staying quiet about what it"
        " declined to add:",
        "",
        "| Bundle | Why |",
        "| --- | --- |",
    ]

    for b in all_bundles:
        if b.get("optIn"):
            lines.append(f"| [`{b['name']}`](#{b['name']}) | {b.get('optInReason', '—')} |")

    lines += [
        "",
        "```bash",
        "gisnix configure myhost --enable services-device-peripherals",
        "```",
        "",
        "### Edit mode",
        "",
        "<kbd>e</kbd> switches the chooser from *which bundles this host"
        " takes* to *what those bundles contain*. In edit mode:",
        "",
        "| Key | |",
        "| --- | --- |",
        "| <kbd>d</kbd> | delete the highlighted package from its module |",
        "| <kbd>a</kbd> | add a package, completing from the catalogue |",
        "| <kbd>g</kbd> | create a new bundle, or a sub-bundle |",
        "",
        "!!! warning \"These edits are not about one host\"",
        "",
        "    Everything above rewrites a module under `software/`, so it"
        " changes **every host whose bundles include it** — up to nine at"
        " once. The chooser says how many before staging each edit, and the"
        " diff at the end is shown per file with the affected hosts listed"
        " beside it.",
        "",
        "Nothing reaches disk while you work: edits are staged and written"
        " only on <kbd>ctrl</kbd>+<kbd>s</kbd>, after the diff. Each one is"
        " then composed in memory, checked with `nix-instantiate --parse` and"
        " read back to confirm it says what was asked, before the file is"
        " replaced atomically. A refusal partway leaves the module untouched.",
        "",
        "The rules the editor works to:",
        "",
        "- an edit is located by **parsing**, never by searching for a string."
        " `firefox` occurs in comments, in embedded shell scripts and in URLs,"
        " and deleting the wrong one yields a module that still evaluates and"
        " quietly installs the wrong software",
        "- a package is removed only when it sits **alone on its line**. The"
        " repository writes one package per line throughout, so this covers"
        " everything that exists; where it does not hold the editor refuses"
        " and says why rather than reaching into a line it does not follow",
        "- an added package is checked against nixpkgs with `nix eval` first."
        " A typo would otherwise give every host taking the bundle an"
        " evaluation error, discovered at the next rebuild rather than here",
        "- some packages are **load-bearing** and cannot be removed at all,"
        " listed as `requiredPackages` in the owning `bundle.json` with the"
        " reason. `fish` is somebody's login shell; `starship`, `fzf`,"
        " `zoxide`, `direnv` and `atuin` are what fish's own"
        " `interactiveShellInit` invokes, so deleting one does not break the"
        " build — it makes every shell opened afterwards print an error, on"
        " every machine, which is the kind of breakage nobody attributes to a"
        " package list",
        "- **packages this flake defines are locked** from deletion, though"
        " the bundles holding them stay entirely optional. The Kartoza"
        " applications, the sandboxed AI tools, and the derivations a module"
        " builds in its own `let` block are all ours: removing the entry that"
        " installs one frees nothing, it just leaves the derivation built by"
        " nothing and reaching no machine. Not wanting them is done by"
        " dropping the bundle, which is a keystroke away. The list is derived"
        " from `overlays/default.nix`, so a package added there tomorrow is"
        " protected without anyone recording it anywhere. A merely *patched*"
        " nixpkgs package — `signal-desktop`, say — is not locked; it is"
        " still in nixpkgs if the entry goes",
        "- a new bundle's **name is derived from its path**, so"
        " `desktop/audio` is `desktop-audio`; a bundle nested inside another"
        " implies its parent automatically. `git add` it — nix reads the flake"
        " from the git tree, so an untracked bundle is invisible",
        "",
        "### It evaluates before it lets you leave",
        "",
        "After writing, `gisnix configure` evaluates the host:",
        "",
        "```bash",
        "nix eval .#nixosConfigurations.<host>.config.system.build.toplevel.drvPath",
        "```",
        "",
        "It builds nothing — this is the same work `nixos-rebuild` does before"
        " it starts fetching. **If it fails, every file the run wrote is put"
        " back**, and the error is shown where it can still be acted on.",
        "",
        "This is not the same check as parsing, and the difference matters."
        " `nix-instantiate --parse` cannot know that a bundle pulls in an"
        " unfree package nothing has allowed, that two modules define the same"
        " option, or that an assertion now fails. Each of those produces a"
        " file that parses perfectly and a machine that will not build.",
        "",
        "That gap was not hypothetical: `services-device-peripherals` could"
        " not be enabled on **any** host, because `hp-scanner.nix` pulls"
        " `hplipWithPlugin` — unfree, and reported by `lib.getName` as"
        " `hplip`, which nothing allowed. Every file parsed. The failure"
        " surfaced at `nixos-rebuild`, after the configuration had been"
        " written. `--no-eval` skips the check.",
        "",
        "### What it guarantees",
        "",
        "| | |",
        "| --- | --- |",
        "| **No unknown names** | the selection is checked against the registry"
        " before anything is rendered. An unknown bundle is an evaluation"
        " error, not a no-op. |",
        "| **No duplicates, one order** | the block is rendered from a set, in"
        " the registry's own order, so toggling one bundle is a one-line diff"
        " whatever state the file arrived in. |",
        "| **Every bundle stated** | the block lists all of them, taken or"
        " commented out under its own description. The file *is* the menu, so"
        " uncommenting a line by hand remains a complete workflow. |",
        "| **Your notes kept** | a comment you wrote about *this machine* comes"
        " back attached to the bundle it annotated. A comment that merely"
        " repeats the registry is dropped, because it is regenerated. |",
        "| **Nothing else touched** | everything outside `bundles = [ … ];` is"
        " copied through byte for byte. |",
        "",
        "After editing, apply it — one bundle per rebuild is the safe way to"
        " add several, because a build that fails then names its own cause:",
        "",
        "```bash",
        "gisnix update myhost",
        "```",
        "",
        "The read-only half of the pair is `gisnix bundles`, which shows what each"
        " one contains without offering to change anything.",
        "",
        "## Why membership is listed rather than implied",
        "",
        "`bundle.json` names its modules explicitly. \"Every `.nix` in the"
        " directory\" would be simpler and wrong: `software/desktop/gis/`"
        " carries several QGIS channels that are alternatives rather than"
        " companions, and importing a directory wholesale would install every"
        " one of them at once.",
        "",
        "Anything in a directory that no bundle claims must be listed as"
        " `unclaimed` — a stated decision rather than an oversight."
        " `utils/check-bundles.py` fails otherwise, because a module nobody"
        " claims is a module nobody installs, and nothing would say so.",
        "",
        "That check earns its keep. Adopting two long-unclaimed modules during"
        " this work found one that was a package derivation filed as a NixOS"
        " module, and another pinned to a placeholder checksum it could never"
        " have built from. Neither had ever worked. **A module nothing imports"
        " is not dormant, it is unverified.**",
        "",
        "## Choices",
        "",
        "A bundle marked `\"selection\": \"one-of\"` holds alternatives, not a"
        " set. A host names the single member it wants instead of taking the"
        " group — `software/locale/` is the clear case, since a machine has one"
        " locale and not eight.",
        "",
        "Each group appears in the `gisnix configure` tree as radio rows nested"
        " under the bundle whose directory contains them — the two kernel rows"
        " sit under `base`, because `software/base/kernel/` is inside"
        " `software/base/`. Picking one unpicks its sibling. What gets written"
        " is the scalar key, not an entry in `bundles`.",
        "",
        "### Kernel",
        "",
        "`software/base/kernel/` is the second choice group, and the one with"
        " teeth:",
        "",
        "| `kernel` | Kernel | OpenZFS | Built where |",
        "|---|---|---|---|",
        "| `\"stable\"` *(default)* | the NixOS default | from the pinned"
        " nixpkgs | prebuilt on Hydra |",
        "| `\"latest\"` | 7.2, from `nixpkgs-master` | 2.4.4, from the same set |"
        " **compiled on the host** |",
        "",
        "Every host here boots from an encrypted ZFS root, so the kernel and"
        " the ZFS package have to come from the same package set: NixOS"
        " resolves the module as"
        " `boot.kernelPackages.${boot.zfs.package.kernelModuleAttribute}`, and"
        " a kernel whose ZFS module does not build gives you a machine that"
        " cannot import its own pool. `\"stable\"` gets that guarantee for"
        " free — nixpkgs marks incompatible pairs broken at evaluation.",
        "",
        "`\"latest\"` needs OpenZFS 2.4.4, which is the first release supporting"
        " the 7.x series and is still master-only; the pinned nixpkgs ships"
        " 2.4.3, whose ceiling is kernel 7.0. Taking the kernel from master"
        " without also taking master's ZFS reintroduces exactly the pair that"
        " does not build.",
        "",
        "A host that pins `boot.kernelPackages` in its own `hardware.nix`"
        " cannot take `\"latest\"`: the pin beats the bundle and only the ZFS"
        " half moves, which is the mismatch the whole arrangement exists to"
        " prevent. The bundle asserts against this and says so by name — drop"
        " the pin, or stay on `\"stable\"`. Most fleets do exactly that: pin a"
        " known-good series and leave `\"latest\"` for the one host tracking"
        " master on purpose.",
        "",
        "The cost is real: master is pre-Hydra, so a host choosing `\"latest\"`"
        " compiles both the kernel and the ZFS module itself, and again"
        " whenever the master pin moves. Rollback is the previous generation"
        " in GRUB, which carries its own matching pair.",
        "",
        "## How they fit together",
        "",
        "Every arrow is an `implies` edge read from `bundle.json`: the bundle"
        " at the tail brings the one at the head with it, so a host naming"
        " only the tail gets both. Nothing here is drawn by hand — this is the"
        " same graph `gisnix bundles --tree` prints in the terminal.",
        "",
        _implication_diagram(all_bundles).rstrip(),
        "",
        "## The bundles",
        "",
    ]

    # Summary table first, for orientation.
    lines.append("| Bundle | Modules | Requires | Pulled in by |")
    lines.append("| --- | --- | --- | --- |")
    for b in all_bundles:
        requires = ", ".join(f"`{d}`" for d in b.get("implies", [])) or "—"
        pulled = ", ".join(f"`{d}`" for d in sorted(implied_by.get(b["name"], []))) or "—"
        count = len(b.get("modules", []))
        kind = " *(choice)*" if b.get("selection") == "one-of" else ""
        lines.append(
            f"| [`{b['name']}`](#{b['name']}) {kind} | {count} | {requires} | {pulled} |"
        )
    lines.append("")

    for b in all_bundles:
        lines.append(f"### {b['name']}")
        lines.append("")
        # Asterisks, not underscores: markdownlint (MD049) rewrites _x_ to
        # *x*, and since this file is regenerated the underscore form came
        # back every time — the generator and the linter undoing each other
        # on every commit.
        lines.append(f"*{b['description']}*")
        lines.append("")
        lines.append(f"`software/{b['path']}/`")
        lines.append("")

        if b.get("selection") == "one-of":
            lines.append(
                "> **A choice, not a set.** A host takes exactly one of these."
            )
            lines.append("")

        if b.get("implies"):
            names = ", ".join(f"`{d}`" for d in b["implies"])
            lines.append(f"Taking this also brings in {names}.")
            lines.append("")

        modules = b.get("modules", [])
        if modules:
            summaries = {m: _first_comment(b["directory"] / m) for m in modules}
            if any(summaries.values()):
                lines.append("| Module | What it is |")
                lines.append("| --- | --- |")
                for m in modules:
                    lines.append(f"| `{m}` | {summaries[m] or '—'} |")
            else:
                # No module here explains itself; a two-column table of blanks
                # is worse than a plain list.
                for m in modules:
                    lines.append(f"- `{m}`")
            lines.append("")

        if b.get("unclaimed"):
            lines.append(
                "Present in the directory but deliberately not installed: "
                + ", ".join(f"`{m}`" for m in b["unclaimed"])
                + "."
            )
            lines.append("")

    total_modules = sum(len(b.get("modules", [])) for b in all_bundles)
    lines += [
        "---",
        "",
        f"{len(all_bundles)} bundles, {total_modules} modules.",
        "",
        "Made with love by [Kartoza](https://kartoza.com) |"
        " [Donate](https://github.com/sponsors/timlinux) |"
        " [GitHub](https://github.com/kartoza/gisnix)",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"  wrote {OUT.relative_to(REPO_ROOT)}  ({len(all_bundles)} bundles)")
    return 0


def _first_comment(module: Path) -> str:
    """The module's one-line description, escaped for a Markdown table.

    The reading itself lives in `utils/lib/bundleinfo.py`, because the
    `gisnix configure` preview pane shows the same sentence for a module whose
    package list cannot be read from source. Two copies would mean the docs
    and the tool describing the same file differently; only the escaping
    below is specific to this page.
    """
    prose = bundleinfo.first_comment(module)
    if not prose:
        return ""
    prose = prose.replace("|", "\\|")
    # Bare URLs are a markdownlint violation (MD034), and these summaries are
    # copied verbatim out of module comments where a bare URL is perfectly
    # normal. Autolink them here rather than letting the linter rewrite the
    # generated file — which it did, and then regeneration undid it, forever.
    return re.sub(r"(?<![(<\w])(https?://[^\s<>()]+)", r"<\1>", prose)


if __name__ == "__main__":
    raise SystemExit(main())
