## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 2.8 pinned at 2.8.2 (nixpkgs 4ad434e521fb).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "2.8" args
