#!/usr/bin/env python3
"""Generate the per-locale NixOS modules from software/locale/locales.json.

One entry in the manifest becomes one `software/locale/locale-<code>.nix`
module and one line in `software/locale/bundle.json`'s "modules" list. The
installer reads the same manifest at runtime to build its locale menu
(installer/screens/host_details.py), so a locale is described exactly once
and the three surfaces cannot drift.

A host takes exactly one locale, named as `locale = "nl-en";` in its
config.nix (or picked in the installer). The code convention is
`<country>` for a native-language desktop and `<country>-en` for an
English desktop with that country's regional formatting — so `nl` is a
Dutch desktop in the Netherlands and `nl-en` is an English desktop that
still formats dates, money and paper sizes the Dutch way.

Run from the repo root after editing the manifest, then regenerate the
bundle docs (pre-commit checks both):

    python3 utils/gen-locales.py
    python3 docs/scripts/generate-bundle-docs.py

Locale names are validated against glibc's SUPPORTED list separately by
utils/check-locales.py — run that too if you add names by hand.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALE_DIR = ROOT / "software" / "locale"
MANIFEST = LOCALE_DIR / "locales.json"
BUNDLE = LOCALE_DIR / "bundle.json"

LC_KEYS = [
    "LC_ADDRESS",
    "LC_IDENTIFICATION",
    "LC_MEASUREMENT",
    "LC_MONETARY",
    "LC_NAME",
    "LC_NUMERIC",
    "LC_PAPER",
    "LC_TELEPHONE",
    "LC_TIME",
]


def render_module(entry: dict) -> str:
    lc = "\n".join(f'    {k} = "{entry["formatLocale"]}";' for k in LC_KEYS)
    dicts = "\n".join(f"    aspellDicts.{lang}" for lang in entry["aspell"])
    return f"""# {entry["label"]}
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{{ pkgs, ... }}:
{{
  time.timeZone = "{entry["timeZone"]}";

  # {entry["uiLocale"]} is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in {entry["formatLocale"]} form.
  i18n.defaultLocale = "{entry["uiLocale"]}";
  i18n.extraLocaleSettings = {{
{lc}
  }};

  services.xserver.xkb = {{
    layout = "{entry["xkbLayout"]}";
    variant = "{entry["xkbVariant"]}";
  }};
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
{dicts}
  ];
}}
"""


def main() -> int:
    entries = json.loads(MANIFEST.read_text())
    codes = {e["code"] for e in entries}
    if len(codes) != len(entries):
        print("gen-locales: duplicate codes in the manifest", file=sys.stderr)
        return 1

    wanted = set()
    for entry in entries:
        path = LOCALE_DIR / f"locale-{entry['code']}.nix"
        path.write_text(render_module(entry))
        wanted.add(path.name)

    # Remove stale modules no longer in the manifest.
    removed = []
    for existing in LOCALE_DIR.glob("locale-*.nix"):
        if existing.name not in wanted:
            existing.unlink()
            removed.append(existing.name)

    bundle = json.loads(BUNDLE.read_text())
    bundle["modules"] = sorted(wanted)
    BUNDLE.write_text(json.dumps(bundle, indent=2) + "\n")

    print(f"✓ wrote {len(entries)} locale modules, updated bundle.json")
    if removed:
        print(f"  removed {len(removed)} stale: {', '.join(sorted(removed))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
