#!/usr/bin/env python3
"""Generate the pinned-QGIS version bundles from qgis-versions.json.

Reads software/desktop/gis/qgis-versions.json (the in-repo cache of
QGIS series -> nixpkgs channel rev -> tarball sha256) and emits one
bundle directory per series under software/desktop/gis/versions/:

    versions/qgis-<slug>/bundle.json      (optIn child of desktop-gis)
    versions/qgis-<slug>/qgis-<slug>.nix  (thin call into qgis-pinned.nix)

Run it after editing the manifest, then regenerate the host config
blocks and the bundle docs (pre-commit checks both):

    python3 utils/gen-qgis-versions.py
    python3 docs/scripts/generate-bundle-docs.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GIS = ROOT / "software" / "desktop" / "gis"
VERSIONS = GIS / "versions"
MANIFEST = GIS / "qgis-versions.json"

MODULE_TEMPLATE = """\
## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS {series} pinned at {version} (nixpkgs {rev_short}).
## Do not edit by hand — edit the manifest and regenerate.
args@{{ pkgs, lib, ... }}: import ../../qgis-pinned.nix "{series}" args
"""


def series_sort_key(series: str) -> tuple[int, int]:
    major, minor = series.split(".")
    return (int(major), int(minor))


def describe(series: str, entry: dict) -> str:
    vintage = not entry["extras"]
    tail = (
        "a vintage Qt4/Python2 build with no extra python packages; may no "
        "longer evaluate or have every binary cached"
        if vintage
        else "installed with the standard python packages from its own "
        "pinned nixpkgs — pure binary-cache hits, no source builds"
    )
    return (
        f"QGIS {series} pinned ({entry['version']}, "
        f"the last {series}.x that nixpkgs shipped), {tail}."
    )


def main() -> int:
    manifest = json.loads(MANIFEST.read_text())
    VERSIONS.mkdir(exist_ok=True)

    wanted_dirs = set()
    for series in sorted(manifest, key=series_sort_key):
        entry = manifest[series]
        slug = series.replace(".", "-")
        dirname = f"qgis-{slug}"
        wanted_dirs.add(dirname)
        bundle_dir = VERSIONS / dirname
        bundle_dir.mkdir(exist_ok=True)

        module = MODULE_TEMPLATE.format(
            series=series,
            version=entry["version"],
            rev_short=entry["rev"][:12],
        )
        (bundle_dir / f"{dirname}.nix").write_text(module)

        bundle = {
            "name": f"desktop-gis-versions-{dirname}",
            "path": f"desktop/gis/versions/{dirname}",
            "description": describe(series, entry),
            "implies": ["desktop-gis"],
            "optIn": True,
            "optInReason": (
                "a frozen historical QGIS; take it only when a project "
                "needs this exact series"
            ),
            "modules": [f"{dirname}.nix"],
        }
        (bundle_dir / "bundle.json").write_text(
            json.dumps(bundle, indent=2) + "\n"
        )
        print(f"  wrote versions/{dirname} ({entry['version']})")

    stale = {
        p.name for p in VERSIONS.iterdir() if p.is_dir()
    } - wanted_dirs
    for name in sorted(stale):
        print(
            f"  WARNING: versions/{name} is not in the manifest — "
            "remove it by hand if it is no longer wanted",
            file=sys.stderr,
        )
    print(f"{len(wanted_dirs)} version bundles generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
