#!/usr/bin/env python3
"""Emit hosts/<name>/config.nix with every bundle listed, most commented out.

The bundle list is read from the registry (software/**/bundle.json) rather
than written down here, so a bundle added tomorrow appears in the next
generated host without anyone remembering to update this file.

The block itself is rendered by utils/lib/hostconfig.py — the same code
`kz configure` uses to rewrite an existing host. That matters: a file this
script writes and a file `kz configure` writes are byte-identical in shape,
so the first edit to a freshly created host produces a one-line diff rather
than a wholesale reformat. Two renderers would have guaranteed the opposite.

The generated host starts minimal: a desktop, a browser, audio and the base
system. Everything else is present as a commented line with a note on what it
gains, so the owner can uncomment one, rebuild, and keep it or back it out.

Usage:
    gen-host-config.py <name> --locale <locale> [--laptop]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "utils" / "lib"))

import hostconfig as H  # noqa: E402

# What a freshly migrated machine gets switched on. Deliberately short: the
# point of the exercise is that the owner adds what they need and knows why
# each thing arrived.
ACTIVE = [
    "base",
    "desktop-environments-cosmic",
    "desktop-browsers",
    "services-system",
]

# Bundles that are load-bearing rather than optional, with the reason. These
# ride along as notes above the bundle, because commenting one out does not
# slim the machine, it breaks it — and the file is where somebody about to do
# that will be looking.
LOAD_BEARING = {
    "base": (
        "Load-bearing. ZFS root and its bootloader — this machine boots from a "
        "ZFS pool, so removing this does not make the install smaller, it makes "
        "it unbootable. Also the login shell and the terminal emulator."
    ),
    "services-system": "Load-bearing: audio, certificates, hardening.",
    "desktop-environments-cosmic": "Load-bearing: the desktop itself.",
    "desktop-browsers": "Load-bearing: a usable machine needs a browser.",
    "services-system-power": "This is a laptop; battery monitoring and suspend.",
}


def header(name: str) -> list[str]:
    return [
        "{",
        f"  # ── {name} ──",
        "  #",
        "  # Generated by `kz create-host`. Only the bundles this machine cannot",
        "  # do without are active; everything else is commented out below, one",
        "  # per line, so it can be enabled a single group at a time:",
        "  #",
        "  #   1. uncomment ONE line",
        f"  #   2. kz update {name}",
        "  #   3. if it builds and behaves, keep it; if not, comment it back out",
        "  #",
        "  # One at a time means a failure names its own cause. Some bundles pull",
        "  # large source trees and take a while on a first build.",
        "  #",
        "  # `kz configure` does the same job from a menu, and is the safer way to",
        "  # change several at once — it shows the diff and checks the result",
        "  # parses before writing anything.",
        "  #",
        "  # See docs/references/bundles.md, or `kz bundles`, for what each holds.",
        "",
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("name")
    ap.add_argument("--locale", required=True)
    ap.add_argument("--laptop", action="store_true")
    args = ap.parse_args()

    active = set(ACTIVE)
    if args.laptop:
        active.add("services-system-power")

    notes = {name: [why] for name, why in LOAD_BEARING.items()}

    lines = header(args.name)
    lines += H.render_block(active, notes=notes)
    lines += [
        "",
        "  # A machine has one locale.",
        f'  locale = "{args.locale}";',
        "}",
    ]

    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
