## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.16 pinned at 3.16.14 (nixpkgs f76bef61369b).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.16" args
