## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.44 pinned at 3.44.12 (nixpkgs c27cdad491a9).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.44" args
