## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.34 pinned at 3.34.15 (nixpkgs 0bd7f95e4588).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.34" args
