# Belgium — English
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{ pkgs, ... }:
{
  time.timeZone = "Europe/Brussels";

  # en_GB.UTF-8 is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in nl_BE.UTF-8 form.
  i18n.defaultLocale = "en_GB.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "nl_BE.UTF-8";
    LC_IDENTIFICATION = "nl_BE.UTF-8";
    LC_MEASUREMENT = "nl_BE.UTF-8";
    LC_MONETARY = "nl_BE.UTF-8";
    LC_NAME = "nl_BE.UTF-8";
    LC_NUMERIC = "nl_BE.UTF-8";
    LC_PAPER = "nl_BE.UTF-8";
    LC_TELEPHONE = "nl_BE.UTF-8";
    LC_TIME = "nl_BE.UTF-8";
  };

  services.xserver.xkb = {
    layout = "be";
    variant = "";
  };
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
    aspellDicts.en
    aspellDicts.nl
  ];
}
