# Hungary — Hungarian
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{ pkgs, ... }:
{
  time.timeZone = "Europe/Budapest";

  # hu_HU.UTF-8 is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in hu_HU.UTF-8 form.
  i18n.defaultLocale = "hu_HU.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "hu_HU.UTF-8";
    LC_IDENTIFICATION = "hu_HU.UTF-8";
    LC_MEASUREMENT = "hu_HU.UTF-8";
    LC_MONETARY = "hu_HU.UTF-8";
    LC_NAME = "hu_HU.UTF-8";
    LC_NUMERIC = "hu_HU.UTF-8";
    LC_PAPER = "hu_HU.UTF-8";
    LC_TELEPHONE = "hu_HU.UTF-8";
    LC_TIME = "hu_HU.UTF-8";
  };

  services.xserver.xkb = {
    layout = "hu";
    variant = "";
  };
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
    aspellDicts.hu
    aspellDicts.en
  ];
}
