# Serbia — Serbian
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{ pkgs, ... }:
{
  time.timeZone = "Europe/Belgrade";

  # sr_RS is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in sr_RS form.
  i18n.defaultLocale = "sr_RS";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "sr_RS";
    LC_IDENTIFICATION = "sr_RS";
    LC_MEASUREMENT = "sr_RS";
    LC_MONETARY = "sr_RS";
    LC_NAME = "sr_RS";
    LC_NUMERIC = "sr_RS";
    LC_PAPER = "sr_RS";
    LC_TELEPHONE = "sr_RS";
    LC_TIME = "sr_RS";
  };

  services.xserver.xkb = {
    layout = "rs";
    variant = "";
  };
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
    aspellDicts.sr
    aspellDicts.en
  ];
}
