# Slovenia — Slovenian
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{ pkgs, ... }:
{
  time.timeZone = "Europe/Ljubljana";

  # sl_SI.UTF-8 is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in sl_SI.UTF-8 form.
  i18n.defaultLocale = "sl_SI.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "sl_SI.UTF-8";
    LC_IDENTIFICATION = "sl_SI.UTF-8";
    LC_MEASUREMENT = "sl_SI.UTF-8";
    LC_MONETARY = "sl_SI.UTF-8";
    LC_NAME = "sl_SI.UTF-8";
    LC_NUMERIC = "sl_SI.UTF-8";
    LC_PAPER = "sl_SI.UTF-8";
    LC_TELEPHONE = "sl_SI.UTF-8";
    LC_TIME = "sl_SI.UTF-8";
  };

  services.xserver.xkb = {
    layout = "si";
    variant = "";
  };
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
    aspellDicts.sl
    aspellDicts.en
  ];
}
