# Romania — Romanian
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{ pkgs, ... }:
{
  time.timeZone = "Europe/Bucharest";

  # ro_RO.UTF-8 is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in ro_RO.UTF-8 form.
  i18n.defaultLocale = "ro_RO.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "ro_RO.UTF-8";
    LC_IDENTIFICATION = "ro_RO.UTF-8";
    LC_MEASUREMENT = "ro_RO.UTF-8";
    LC_MONETARY = "ro_RO.UTF-8";
    LC_NAME = "ro_RO.UTF-8";
    LC_NUMERIC = "ro_RO.UTF-8";
    LC_PAPER = "ro_RO.UTF-8";
    LC_TELEPHONE = "ro_RO.UTF-8";
    LC_TIME = "ro_RO.UTF-8";
  };

  services.xserver.xkb = {
    layout = "ro";
    variant = "";
  };
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
    aspellDicts.ro
    aspellDicts.en
  ];
}
