# Sweden — Swedish
#
# Generated by utils/gen-locales.py from software/locale/locales.json.
# Do not edit by hand — edit the manifest and regenerate.
{ pkgs, ... }:
{
  time.timeZone = "Europe/Stockholm";

  # sv_SE.UTF-8 is the desktop language; the LC_* block below keeps
  # dates, money, measurements and paper size in sv_SE.UTF-8 form.
  i18n.defaultLocale = "sv_SE.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "sv_SE.UTF-8";
    LC_IDENTIFICATION = "sv_SE.UTF-8";
    LC_MEASUREMENT = "sv_SE.UTF-8";
    LC_MONETARY = "sv_SE.UTF-8";
    LC_NAME = "sv_SE.UTF-8";
    LC_NUMERIC = "sv_SE.UTF-8";
    LC_PAPER = "sv_SE.UTF-8";
    LC_TELEPHONE = "sv_SE.UTF-8";
    LC_TIME = "sv_SE.UTF-8";
  };

  services.xserver.xkb = {
    layout = "se";
    variant = "";
  };
  # Derive the virtual-console keymap from the X keyboard layout above, so
  # the TTY matches the desktop without naming a separate console keymap.
  console.useXkbConfig = true;

  environment.systemPackages = with pkgs; [
    aspell
    aspellDicts.sv
    aspellDicts.en
  ];
}
