## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 2.4 pinned at 2.4.0 (nixpkgs 86744fef91ab).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "2.4" args
