## Generated by utils/gen-qgis-versions.py from qgis-versions.json.
## QGIS 3.32 pinned at 3.32.3 (nixpkgs 9957cd48326f).
## Do not edit by hand — edit the manifest and regenerate.
args@{ pkgs, lib, ... }: import ../../qgis-pinned.nix "3.32" args
