"""Turns a filled-in InstallState into the files a new machine needs: its
host directory, its user file, and the tiny per-machine flake that pins
gisnix and calls `gisnix.lib.mkHost`.

Reuses utils/lib/hostconfig.py for the bundles block — the SAME renderer
`gisnix configure` and `gisnix create-host` use, so a host the installer creates and
one `gisnix create-host` creates are byte-identical in shape.
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

from .repo import GISNIX_ROOT
from .state import InstallState, STORAGE_XFS_SINGLE, STORAGE_ZFS_ENCRYPTED_SINGLE, STORAGE_ZFS_MULTI

if GISNIX_ROOT is not None:
    sys.path.insert(0, str(GISNIX_ROOT / "utils" / "lib"))
import hostconfig as H  # noqa: E402

LOAD_BEARING = {
    "base": (
        "Load-bearing. ZFS root and its bootloader — this machine boots from "
        "a ZFS pool, so removing this does not make the install smaller, it "
        "makes it unbootable. Also the login shell and the terminal emulator."
    ),
    "services-system": "Load-bearing: audio, certificates, hardening.",
    "desktop-environments-cosmic": "Load-bearing: the desktop itself.",
    "desktop-browsers": "Load-bearing: a usable machine needs a browser.",
    "services-device-input-kanata": (
        "On by default: gisnix's keyboard remapping (home-row mods, nav layer). "
        "Needs no vendor hardware; remove the line if you'd rather type raw."
    ),
}


def render_config_nix(state: InstallState) -> str:
    lines = [
        "{",
        f"  # ── {state.hostname} ──",
        "  #",
        "  # Generated by the gisnix installer. Only the bundles chosen during",
        "  # install are active; everything else is commented out below, one",
        "  # per line — uncomment, `gisnix update`, keep it if it builds and",
        "  # behaves, or `gisnix configure` for a menu instead of hand-editing.",
        "",
    ]
    lines += H.render_block(state.bundles, notes={k: [v] for k, v in LOAD_BEARING.items()})
    lines += [
        "",
        f'  locale = "{state.locale}";',
        f'  bootTheme = "{state.boot_theme}";',
        "}",
    ]
    return "\n".join(lines) + "\n"


def render_default_nix(state: InstallState) -> str:
    return f"""{{
  lib,
  hostname,
  gisnixRoot,
  ...
}}:
{{
  nixpkgs.config.allowUnfree = false;

  imports = [
    ./disks.nix
    ./hardware.nix

    ../../users/{state.username}.nix

    (gisnixRoot + "/software/locale/locale-{state.locale}.nix")

    (gisnixRoot + "/profiles/common.nix")
    (gisnixRoot + "/profiles/cosmic-desktop.nix")
    (gisnixRoot + "/profiles/kartoza.nix")
    (gisnixRoot + "/profiles/stylix.nix")
    (gisnixRoot + "/profiles/services.nix")
  ];

  networking.hostName = hostname;
}}
"""


def render_desktop_nix() -> str:
    return "{ ... }:\n{\n  imports = [ ];\n}\n"


def render_services_nix() -> str:
    return "{ ... }:\n{ }\n"


#: Same generic VM/UEFI-friendly hardware profile as hosts/example/hardware.nix
#: — real hardware auto-detection is deliberately out of scope for v1 (see
#: SPECIFICATION.md); this is the same simplification tuinix's own installer
#: makes. Refine by hand for exotic hardware.
_HARDWARE_NIX = """{
  modulesPath,
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.grub = {
    devices = [ "nodev" ];
    efiSupport = true;
    efiInstallAsRemovable = true;
  };

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "virtio_blk"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
    "nvme"
    "ehci_pci"
    "usbhid"
    "usb_storage"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ "virtio_gpu" ];
  boot.kernelModules = [
    "kvm-intel"
    "kvm-amd"
  ];
  boot.extraModulePackages = [ ];
  swapDevices = [ ];

  # ZFS refuses to import a pool without one — it's how a pool tells two
  # machines apart, which matters the moment a disk moves between them.
  # Generated fresh for this machine at install time (secrets.token_hex,
  # not derived from the ISO's own /etc/machine-id, which every machine
  # booting the same image would otherwise share) — not hand-picked, and
  # deliberately not reused from any template, or every host this
  # installer ever creates would collide on the same id.
  networking.hostId = "%(host_id)s";

  # Whatever size you picked on the installer's own welcome screen — carried
  # over so the first real boot doesn't spring the same "why is this text
  # enormous" surprise the installer itself shipped with by default.
  console.font = "ter-v%(console_font_size)sn";
  console.packages = [ pkgs.terminus_font ];
  console.earlySetup = true;

%(zfs_block)s

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.graphics.enable = true;

  services.qemuGuest.enable = true;
  services.spice-vdagentd.enable = true;
}
"""

_ZFS_BLOCK = """  # forceImportRoot is set centrally in software/base/zfs.nix, not here.
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.requestEncryptionCredentials = %(encrypted)s;
  boot.initrd.systemd.enable = true;
  services.zfs.autoScrub.enable = true;"""


def render_hardware_nix(state: InstallState) -> str:
    if state.storage_mode == STORAGE_XFS_SINGLE:
        zfs_block = "  # No ZFS — plain XFS root (see disks.nix)."
    else:
        encrypted = (
            "true"
            if state.storage_mode == STORAGE_ZFS_ENCRYPTED_SINGLE or state.zfs_multi_encrypted
            else "false"
        )
        zfs_block = _ZFS_BLOCK % {"encrypted": encrypted}
    return _HARDWARE_NIX % {
        "zfs_block": zfs_block,
        "console_font_size": state.console_font_size,
        "host_id": secrets.token_hex(4),
    }


def render_disks_nix(state: InstallState) -> str:
    if state.storage_mode == STORAGE_ZFS_ENCRYPTED_SINGLE:
        return (
            "# ZFS, single disk, encrypted (AES-256-GCM passphrase). Generated by the gisnix installer.\n"
            '{ gisnixRoot, ... }:\n'
            f'import (gisnixRoot + "/templates/disko/zfs-encrypted-single.nix") {{ device = "{state.disks[0]}"; }}\n'
        )
    if state.storage_mode == STORAGE_XFS_SINGLE:
        return (
            "# XFS, single disk, unencrypted. Generated by the gisnix installer.\n"
            '{ gisnixRoot, ... }:\n'
            f'import (gisnixRoot + "/templates/disko/xfs-single.nix") {{ device = "{state.disks[0]}"; }}\n'
        )
    if state.storage_mode == STORAGE_ZFS_MULTI:
        devices = ", ".join(f'"{d}"' for d in state.disks)
        encrypted = "true" if state.zfs_multi_encrypted else "false"
        return (
            f"# ZFS, {len(state.disks)} disks, {state.zfs_raid_mode}. Generated by the gisnix installer.\n"
            '{ gisnixRoot, ... }:\n'
            f'import (gisnixRoot + "/templates/disko/zfs-multi.nix") {{\n'
            f"  devices = [ {devices} ];\n"
            f'  mode = "{state.zfs_raid_mode}";\n'
            f"  encrypted = {encrypted};\n"
            "}\n"
        )
    raise ValueError(f"unknown storage mode: {state.storage_mode}")


def render_user_nix(state: InstallState) -> str:
    keys = "\n".join(f'      "{k}"' for k in state.ssh_public_keys)
    keys_block = f"[\n{keys}\n    ]" if state.ssh_public_keys else "[ ]"
    return f"""{{ pkgs, ... }}:
{{
  users.users.{state.username} = {{
    isNormalUser = true;
    description = "{state.full_name or state.username}";
    extraGroups = [ "wheel" "networkmanager" "video" "input" ];
    shell = pkgs.bash;
    hashedPassword = "{state.password_hash}";
    openssh.authorizedKeys.keys = {keys_block};
  }};

  # kanata (services-device-input-kanata, on by default) writes remapped
  # keystrokes through /dev/uinput — see software/services/device/
  # input-kanata/kanata-keyboard.nix's own header for the group this needs.
  users.groups.uinput.members = [ "{state.username}" ];
}}
"""


def render_flake_nix(
    state: InstallState,
    gisnix_flake_ref: str = "github:kartoza/gisnix",
    *,
    install: bool = False,
) -> str:
    """`install=True` adds a second, install-only nixosConfiguration that
    pulls COSMIC from stable nixpkgs instead of nixpkgs-unstable (see
    overlays/default.nix's stableCosmic) — nixos-26.05 already carries
    cosmic-comp 1.2.0, fully built on cache.nixos.org, so the very first
    install doesn't compile a desktop from source just to get one running.
    installer_run.py builds against THAT output, then overwrites this file
    with the plain (install=False) version before copying it to
    ~/nixos-config — `gisnix update` from then on rebuilds from the config
    above, unstable-pinned as always, which is deliberately where
    bleeding-edge COSMIC actually lands."""
    install_config = (
        f"""

    # Install-only — see render_flake_nix's own docstring in
    # installer/writer.py. Not present in the copy that ends up in
    # ~/nixos-config; safe to ignore if you're reading this after boot.
    nixosConfigurations."{state.hostname}-install" = gisnix.lib.mkHost "{state.hostname}" {{
      hostPath = ./hosts/{state.hostname};
      stableCosmic = true;
    }};"""
        if install
        else ""
    )
    return f"""{{
  description = "{state.hostname} — a gisnix machine";

  inputs.gisnix.url = "{gisnix_flake_ref}";

  outputs = {{ self, gisnix, ... }}: {{
    nixosConfigurations.{state.hostname} = gisnix.lib.mkHost "{state.hostname}" {{
      hostPath = ./hosts/{state.hostname};
    }};{install_config}
  }};
}}
"""


def write_existing_host(state: InstallState, target_root: Path) -> None:
    """Copy an already-known host profile (state.existing_host_name) from
    this gisnix checkout into target_root, rather than generating a fresh
    one — for reinstalling a machine whose profile is already committed
    somewhere (this gisnix's own hosts/, or a downstream layer's)."""
    import shutil

    if GISNIX_ROOT is None or state.existing_host_name is None:
        raise RuntimeError("no existing host to copy — is GISNIX_ROOT set?")

    src = GISNIX_ROOT / "hosts" / state.existing_host_name
    dst = target_root / "hosts" / state.existing_host_name
    shutil.copytree(src, dst, dirs_exist_ok=True)

    (target_root / "users").mkdir(parents=True, exist_ok=True)
    user_src = GISNIX_ROOT / "users" / f"{state.username}.nix"
    if user_src.exists():
        shutil.copy2(user_src, target_root / "users" / f"{state.username}.nix")
    else:
        (target_root / "users" / f"{state.username}.nix").write_text(render_user_nix(state))

    state.hostname = state.existing_host_name
    (target_root / "flake.nix").write_text(render_flake_nix(state, install=True))


def write_new_host(state: InstallState, target_root: Path) -> None:
    """Write hosts/<name>/*, users/<name>.nix and flake.nix under
    target_root — the tiny per-machine flake that will live at
    ~/nixos-config on the installed system."""
    host_dir = target_root / "hosts" / state.hostname
    host_dir.mkdir(parents=True, exist_ok=True)
    (target_root / "users").mkdir(parents=True, exist_ok=True)

    (host_dir / "config.nix").write_text(render_config_nix(state))
    (host_dir / "default.nix").write_text(render_default_nix(state))
    (host_dir / "desktop.nix").write_text(render_desktop_nix())
    (host_dir / "services.nix").write_text(render_services_nix())
    (host_dir / "hardware.nix").write_text(render_hardware_nix(state))
    (host_dir / "disks.nix").write_text(render_disks_nix(state))
    (target_root / "users" / f"{state.username}.nix").write_text(render_user_nix(state))
    (target_root / "flake.nix").write_text(render_flake_nix(state, install=True))
